# Read config documentation at https://goreleaser.com
project_name: temporalite
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - main: ./cmd/temporalite
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
